### ISSUE TITLE
 What will be the method used to track attendance?

### ISSUE THREAD

**Issue by corlaez** [corlaez/asistencia#2]
Will the attendee opt in to track his attendance? Like say, using their own cellphone.

Or Will there be a clerk in charge of tracking attendance?

 How precise do we need attendance to be?

**Comment by JessicaMP** [comment]
The assistant does not need it and I doubt that he will check what days I was or not at the agape.

If there is a person (Luz Allccaco) fill out a separate report to remind the leaders in case they do not complete their attendance.

If by precise you mean that it is restrictive, for example yesterday there was agape but I upload that information to the system tomorrow it should be allowed or in case of having an assistance from months ago the system should let me make changes.

**Comment by corlaez** [comment]
Nah I think that the answer is what we were talking the other day.
It will be executed by a given person (the Leader) and he will make sure assistance is registered

**Comment by JessicaMP** [comment]
Nah, according to your flow exist other person maybe is not the leader but this person need review different assists

**Comment by corlaez** [comment]
Admin, does everything

Leader creates groups, creates participants, records attendance for participants in their group, they can can offer an accept being an owner or a secondary leader for a group.

Groups have:
* A creator
* An owner (the creator by default)
* Zero, One or more secondary leaders. They have restricted access in a group but they can for example create attendance records.

We also have a different role, I can’t remember the name, that can view all attendance of all groups

**Comment by JessicaMP** [comment]
I can’t remember the name but is similar role supervisor.

**Comment by corlaez** [comment]
Leaders and secondary leaders track attendance.
For more about roles, see the roles ticket.
