### ISSUE TITLE
 Do we need to think about aggregating multiple venues attendance early on?

### ISSUE THREAD

**Issue by corlaez** [corlaez/asistencia#3]

**Comment by JessicaMP** [comment]
If by multiple places you mean the devices on which the web will be viewed, then the answer is YES, since it should be a responsive web with a focus on mobile, ipad and laptop (in that order)

**Comment by corlaez** [comment]
No, I am talking about the place the meeting will take place. Like a given temple or even a room number, or something like a zoom id, any reference works

**Comment by JessicaMP** [comment]
Actually the meeting is online usually use zoom but before quarantine use room in temple.

**Comment by corlaez** [comment]
Right, but I am thinking in generic terms, if that makes sense.
It may be an optional field but i think there is value on having it

**Comment by JessicaMP** [comment]
The reason is for business marketing or for identify where is the target audiences

**Comment by corlaez** [comment]
ok. let's close it as yes, there is an optional references to the venue location (or link)
